TodoAppWebApi.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TodoAppWebApi.MVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }


     
    }
}

TodoAppWebApi.MVC/Controllers/TaskController.cs
using Ertglr.Libraries.Common.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TodoAppWebApi.ENTITIES.EntityClass;
using TodoAppWebApi.ENTITIES.ViewModels;
using TodoAppWebApi.MVC.Helpers;

namespace TodoAppWebApi.MVC.Controllers
{
    public class TaskController : Controller
    {
        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(TaskRequestViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = RestSharpHelperFactory.TodoApiHelper.Post<TaskResponseViewModel>("/Task/CreateTask",model);
                    return RedirectToAction("Index","User");

            }

            return View(model);
        }


        public ActionResult Update(int id)
        {
           var task = RestSharpHelperFactory.TodoApiHelper.Get<ResponseObject<TaskResponseViewModel>>("/Task/GetTaskById/"+id);
            
            return View(task.Data.Result);
        }

        [HttpPost]
        public ActionResult Update(TaskRequestViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = RestSharpHelperFactory.TodoApiHelper.Put<TaskResponseViewModel>("/Task/UpdateTask", model);

                if (response.IsSuccessful==true && response.StatusCode==System.Net.HttpStatusCode.OK)
                {
                     return RedirectToAction("Index", "User");

                }

                return View(response.ErrorMessage);

            }

            return View(model);
        }


        public ActionResult Delete(int id)
        {
            var task = RestSharpHelperFactory.TodoApiHelper.Get<TaskResponseViewModel>("/Task/GetTaskById/" + id);

            return View();
        }

        [HttpPost]
        public ActionResult Delete(TaskRequestViewModel model)
        {
            var response = RestSharpHelperFactory.TodoApiHelper.Delete<TaskResponseViewModel>("/Task/DeleteTask/"+model.ID);

            return View();
        }
    }
}

TodoAppWebApi.MVC/Controllers/UserController.cs
using Ertglr.Libraries.Common.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TodoAppWebApi.ENTITIES.EntityClass;
using TodoAppWebApi.ENTITIES.ViewModels;
using TodoAppWebApi.MVC.Helpers;

namespace TodoAppWebApi.MVC.Controllers
{
    public class UserController : Controller
    {

        public ActionResult Index()
        {
            if (Session["login"] != null)
            {
                var user = Session["login"] as LoginResponseViewModel;
                var response = RestSharpHelperFactory.TodoApiHelper.Get<ResponseObject<List<TaskResponseViewModel>>>("/Task/GetTasks/" + user.Username);


                return View(response.Data.Result);

            }
            return RedirectToAction("Login");
        }

        public ActionResult Login()
        {

            return View();
        }


        [HttpPost]
        public ActionResult Login(LoginRequestViewModel model)
        {
            if (ModelState.IsValid)
            {
                LoginRequestViewModel postData = new LoginRequestViewModel()
                {
                    Email = model.Email,
                    Password = model.Password
                };

                var response = RestSharpHelperFactory.TodoApiHelper.Post<ResponseObject<LoginResponseViewModel>>("/User/Authenticate", postData);

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    if (response.Data != null && response.Data.IsSuccess == true)
                    {
                        Session["login"] = response.Data.Result;
                        return RedirectToAction("Index");
                    }
                }
            }

            return View(model);
        }


        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(RegisterRequestViewModel user)
        {

            var response = RestSharpHelperFactory.TodoApiHelper.Post<ResponseObject<RegisterResponseViewModel>>("/User/PostUser", user);
            if (response.IsSuccessful)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(response);

        }

        public ActionResult UpdateUser(Guid id)
        {
            var response = RestSharpHelperFactory.TodoApiHelper.Get<List<ResponseObject<RegisterRequestViewModel>>>("/User/GetUserById/" + id);

            return View(response);
        }

        [HttpPost]
        public ActionResult UpdateUser(RegisterRequestViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = RestSharpHelperFactory.TodoApiHelper.Put<ResponseObject<RegisterRequestViewModel>>("/User/PutUser", model);
                if (response.IsSuccessful)
                {
                    return RedirectToAction("Index");
                }

            }

            return View();
        }

    }
}

TodoAppWebApi.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<h2>TodoApp'e Hoş Geldiniz</h2>


<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4"><strong>Merhaba</strong></h1>
        <p class="lead">Sayfaları görebilmek için lütfen giriş yapınız. Giriş için yukarıdaki Giriş Yap butonuna tıklayabilirsiniz.</p>
        <p>Eğer kayıtlı değilseniz Kayıt Ol butonuna tıklayarak kayıt sayfasına gidebilirsiniz.</p>
    </div>
</div>

TodoAppWebApi.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TodoApp-RestSharp</title>

    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Anasayfa", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="nav-item">@Html.ActionLink("Giriş Yap", "Login", "User", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Kayıt Ol", "Register", "User", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - TodoApp-RestSharp</p>
        </footer>
    </div>


    <script src="~/Scripts/jquery-2.2.2.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>

TodoAppWebApi.MVC/Views/Task/Create.cshtml
@model TodoAppWebApi.ENTITIES.ViewModels.TaskRequestViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TaskRequestViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TodoAppWebApi.MVC/Views/Task/Delete.cshtml
@model TodoAppWebApi.ENTITIES.ViewModels.TaskRequestViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaskRequestViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TodoAppWebApi.MVC/Views/Task/Tasks.cshtml
@using Ertglr.Libraries.Common.Entities

@model IEnumerable<TodoAppWebApi.ENTITIES.ViewModels.TaskResponseViewModel>

@{
    ViewBag.Title = "Tasks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tasks</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.CreatedOn)*@
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.ModifiedOn)*@
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Username)*@
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.IsCompleted)*@
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.DueDate)*@
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Data.Result) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsCompleted)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DueDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Update", new { id=item.ID }) |
            @*@Html.ActionLink("Details", "Details", new { id=item.ID }) |*@
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

TodoAppWebApi.MVC/Views/Task/Update.cshtml
@model TodoAppWebApi.ENTITIES.ViewModels.TaskResponseViewModel

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TaskResponseViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        @Html.HiddenFor(i=>i.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

            

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsCompleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsCompleted)
                    @Html.ValidationMessageFor(model => model.IsCompleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TodoAppWebApi.MVC/Views/User/Index.cshtml
@using Ertglr.Libraries.Common.Entities
@using TodoAppWebApi.ENTITIES.ViewModels

@model IEnumerable<TaskResponseViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create","Task")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsCompleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DueDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsCompleted)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DueDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Update","Task",new {  id=item.ID},new { @class="btn btn-small btn-warning"}) |
            @*@Html.ActionLink("Details", "Details","Task", new {  id=item.ID }) | oluşturulacak*@
            @Html.ActionLink("Delete", "Delete","Task", new { id=item.ID },new { @class="btn btn-small btn-danger"})
        </td>
    </tr>
}

</table>

TodoAppWebApi.MVC/Views/User/Login.cshtml
@model TodoAppWebApi.ENTITIES.ViewModels.LoginRequestViewModel
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row text-center my-3">
    <div class="col-sm-12">
        <h2 class="display-4">Kayıt sayfasına hoşgeldiniz...</h2>
    </div>
</div>




<div class="row my-5">
    <div class=" col-sm-4 offset-4 login-box p-5">
        @using (Html.BeginForm())
        {
            if (Model == null)
            {
                <div class="form-group row">
                    <div class="col-sm-12">
                        <h5>Mail adresi veya şifre geçersiz...</h5>
                    </div>
                </div>
            }
            <div class="form-group row">
                @Html.LabelFor(i => i.Email, new { @class = "col-sm-4 col-form-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(i => i.Email, null, new { id = "txtMail", @class = "form-control", @placeholder = "mail@mail.com" })
                    @Html.ValidationMessageFor(i => i.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(i => i.Password, new { @class = "col-sm-4 col-form-label" })
                <div class="col-sm-8">
                    @Html.PasswordFor(i => i.Password, new { id = "pswPassword", @class = "form-control", @placeholder = "Şifrenizi giriniz..." })
                    @Html.ValidationMessageFor(i => i.Password, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-12">
                    <input id="btnGonder" type="submit" value="Giriş" class="btn btn-success btn-block" />
                </div>
            </div>
        }
    </div>
</div>

TodoAppWebApi.MVC/Views/User/Register.cshtml
@model TodoAppWebApi.ENTITIES.ViewModels.RegisterRequestViewModel

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Register</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control", id = "txtFirstname" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control", id = "txtLastname" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", id = "txtUsername" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", id = "txtEmail" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", id = "txtPassword" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control", id = "txtConfirmPassword" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Oluştur" class="btn btn-danger" id="btnEkle" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TodoAppWebApi.MVC/Views/User/UpdateUser.cshtml
@model TodoAppWebApi.ENTITIES.ViewModels.RegisterRequestViewModel

@{
    ViewBag.Title = "UpdateUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UpdateUser</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RegisterRequestViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>